### ISSUE TITLE
Executing pyfs_stress fails with ImportError: cannot import name 'DYNAMO_PATH'

### ISSUE THREAD

**Issue by raghavanv90** [samuelsh/pyFstress#2]
[root@init79a-35 pyfs_stress]# ./fileops_server.py -c 10.20.45.2 --export nfstarget --tenants -m nfs3 10.20.19.205
2021-01-05 05:51:22,500;INFO - [__main__]: Loading Test Configuration
2021-01-05 05:51:22,501;INFO - [__main__]: Setting passwordless SSH connection
2021-01-05 05:51:22,504;INFO - [__main__]: Flushing locking DB
2021-01-05 05:51:22,506;INFO - [__main__]: Starting SUB Logger process
2021-01-05 05:51:22,509;INFO - [__main__]: Controller started
2021-01-05 05:51:32,520;INFO - [__main__]: Setting SSH connection to 10.20.45.2
2021-01-05 05:51:32,525;INFO - [__main__]: Deploying to 10.20.45.2
2021-01-05 05:51:35,812;INFO - [__main__]: Done deploying clients: ['10.20.45.2']
2021-01-05 05:51:36,372;INFO - [__main__]: SSH command response with 1 processes on client 10.20.45.2
Traceback (most recent call last):
  File "/root/qa/dynamo/client/dynamo_starter.py", line 9, in <module>
    from generic_mounter import Mounter
  File "/root/qa/dynamo/client/generic_mounter.py", line 16, in <module>
    from config import DYNAMO_PATH
ImportError: cannot import name 'DYNAMO_PATH'
2021-01-05 05:51:37,996;INFO - [__main__]: SSH command response with 0 processes on client 10.20.45.2
2021-01-05 05:51:39,625;INFO - [__main__]: SSH command response with 0 processes on client 10.20.45.2

**Comment by samuelsh** [comment]
Fixed in ebedffe49de11d1ff5d88af17b3b8f1816e48bd8
